// Shared Typst template for consolidated docs in this workspace.
//
// Every file generated by /consolidate imports `workspace-doc`, `topic`, and
// `batch-table` from this template. Restyle here and every consolidated doc
// inherits the change on next compile.
//
// Uses the cmarker package (https://typst.app/universe/package/cmarker)
// to render question/ideas markdown files verbatim. cmarker is fetched
// automatically from Typst Universe on first compile — no manual install.
//
// IMPORTANT: compile with `typst compile --root .` from the repo root so
// that `read("../questions/...")` can reach files outside `outputs/`.
// Without --root, Typst sandboxes the project to the entry file's
// directory and refuses to read parent paths.
//
// Fonts default to DejaVu / Liberation, which ship on most Linux distros.
// On macOS / Windows or to match a personal brand, edit the `set text`
// lines below.

#import "@preview/cmarker:0.1.6": render as md

#let workspace-doc(
  title: [Untitled],
  scope: "",
  generated: datetime.today().display("[year]-[month]-[day]"),
  slugs: (),
  body,
) = {
  set document(title: if type(title) == str { title } else { "Consolidated topics" })
  set page(
    paper: "a4",
    margin: (x: 2.2cm, y: 2.4cm),
    numbering: "1",
    footer: context align(center, text(size: 8pt, fill: gray)[
      page #counter(page).display() · generated #generated
    ]),
  )
  set text(font: ("DejaVu Sans", "Liberation Sans"), size: 10.5pt)
  set par(justify: true, leading: 0.62em)
  show heading.where(level: 1): set text(size: 20pt, weight: "bold")
  show heading.where(level: 2): set text(size: 14pt, weight: "bold")
  show heading.where(level: 3): set text(size: 12pt, weight: "bold")
  show heading: it => { v(0.4em); it; v(0.2em) }
  show raw.where(block: true): set block(
    fill: rgb("#f4f4f4"),
    inset: 8pt,
    radius: 3pt,
    width: 100%,
  )
  show raw: set text(font: ("DejaVu Sans Mono", "Liberation Mono"), size: 9pt)
  show link: set text(fill: rgb("#1a4d8f"))

  // Title page
  align(center + horizon)[
    #text(size: 26pt, weight: "bold")[#title]
    #v(0.6em)
    #if scope != "" [
      #text(size: 11pt, fill: gray)[#scope]
    ]
    #v(2em)
    #text(size: 9pt, fill: gray)[
      Generated #generated · #slugs.len() topic#if slugs.len() != 1 ["s"]
    ]
  ]
  pagebreak()

  // Contents
  outline(title: [Contents], depth: 2, indent: auto)
  pagebreak()

  body
}

// Render a batch summary table at the top of the document, listing each
// topic's slug alongside its prompt. `items` is an array of (slug, prompt)
// tuples. `label` defaults to "Batch" but can be "Batch 1", etc.
#let batch-table(label: "Batch", items: ()) = {
  heading(level: 1, [#label — Summary])
  v(0.4em)
  table(
    columns: (auto, 1fr),
    align: (left, left),
    stroke: 0.5pt + gray,
    inset: 7pt,
    table.header(
      [*Slug*], [*Prompt*],
    ),
    ..items.map(((slug, prompt)) => (raw(slug), prompt)).flatten()
  )
  pagebreak(weak: true)
}

// Render one topic as a Prompt + Output pair from the markdown source files.
// Paths are relative to the location of the generated .typ file (i.e.
// "../questions/<slug>.md" from inside outputs/).
//
// `date` and `model` are optional; when either is given, a metadata line is
// shown below the Output heading identifying when and by which model the
// response was generated.
#let topic(slug, question-path, ideas-path, date: none, model: none) = {
  pagebreak(weak: true)
  heading(level: 1, [Topic: #raw(slug)])
  v(0.3em)

  heading(level: 2, [Prompt])
  md(read(question-path))

  v(0.6em)
  heading(level: 2, [Output])
  if date != none or model != none {
    let bits = ()
    if date != none { bits.push("Generated " + date) }
    if model != none { bits.push("Model: " + model) }
    text(size: 9pt, fill: gray)[#bits.join(" · ")]
    v(0.4em)
  }
  md(read(ideas-path))
}
