// Shared Typst template for consolidated docs in this workspace.
//
// Every file generated by /consolidate imports `workspace-doc` and `topic`
// from this template. Restyle here and every consolidated doc inherits
// the change on next compile.
//
// Uses the cmarker package (https://typst.app/universe/package/cmarker)
// to render question/ideas markdown files verbatim. cmarker is fetched
// automatically from Typst Universe on first compile — no manual install.
//
// IMPORTANT: compile with `typst compile --root .` from the repo root so
// that `read("../questions/...")` can reach files outside `outputs/`.
// Without --root, Typst sandboxes the project to the entry file's
// directory and refuses to read parent paths.
//
// Fonts default to DejaVu / Liberation, which ship on most Linux distros.
// On macOS / Windows or to match a personal brand, edit the `set text`
// lines below.

#import "@preview/cmarker:0.1.6": render as md

#let workspace-doc(
  title: [Untitled],
  scope: "",
  generated: datetime.today().display("[year]-[month]-[day]"),
  slugs: (),
  body,
) = {
  set document(title: if type(title) == str { title } else { "Consolidated topics" })
  set page(
    paper: "a4",
    margin: (x: 2.2cm, y: 2.4cm),
    numbering: "1",
    footer: context align(center, text(size: 8pt, fill: gray)[
      page #counter(page).display() · generated #generated
    ]),
  )
  set text(font: ("DejaVu Sans", "Liberation Sans"), size: 10.5pt)
  set par(justify: true, leading: 0.62em)
  show heading.where(level: 1): set text(size: 20pt, weight: "bold")
  show heading.where(level: 2): set text(size: 14pt, weight: "bold")
  show heading.where(level: 3): set text(size: 12pt, weight: "bold")
  show heading: it => { v(0.4em); it; v(0.2em) }
  show raw.where(block: true): set block(
    fill: rgb("#f4f4f4"),
    inset: 8pt,
    radius: 3pt,
    width: 100%,
  )
  show raw: set text(font: ("DejaVu Sans Mono", "Liberation Mono"), size: 9pt)
  show link: set text(fill: rgb("#1a4d8f"))

  // Title page
  align(center + horizon)[
    #text(size: 26pt, weight: "bold")[#title]
    #v(0.6em)
    #if scope != "" [
      #text(size: 11pt, fill: gray)[#scope]
    ]
    #v(2em)
    #text(size: 9pt, fill: gray)[
      Generated #generated · #slugs.len() topic#if slugs.len() != 1 ["s"]
    ]
  ]
  pagebreak()

  // Contents
  outline(title: [Contents], depth: 2, indent: auto)
  pagebreak()

  body
}

// Render one topic as a Question + Ideas pair from the markdown source files.
// Paths are relative to the location of the generated .typ file (i.e.
// "../questions/<slug>.md" from inside outputs/).
#let topic(slug, question-path, ideas-path) = {
  pagebreak(weak: true)
  heading(level: 1, [Topic: #raw(slug)])
  v(0.3em)

  heading(level: 2, [Question])
  md(read(question-path))

  v(0.6em)
  heading(level: 2, [Ideas])
  md(read(ideas-path))
}
